# Generated by Django 4.0.5 on 2022-07-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionsbank',
            old_name='subjectID',
            new_name='subject_id',
        ),
        migrations.RenameField(
            model_name='questionsbank',
            old_name='topicID',
            new_name='topic_id',
        ),
        migrations.AlterField(
            model_name='questionsbank',
            name='choice',
            field=models.CharField(choices=[('N', '------'), ('A', 'Option-A'), ('B', 'Option-B'), ('C', 'Option-C'), ('D', 'Option-D')], db_column='UserChoice', default='N', max_length=1),
        ),
        migrations.AlterModelTable(
            name='leaderboard',
            table='Leaderboard',
        ),
        migrations.AlterModelTable(
            name='questionsbank',
            table='QuestionBank',
        ),
        migrations.AlterModelTable(
            name='student_review',
            table='Student_review',
        ),
        migrations.AlterModelTable(
            name='subjectdetail',
            table='SubjectDetail',
        ),
        migrations.AlterModelTable(
            name='topicmaster',
            table='TopicMaster',
        ),
    ]
